// Shared employee data for consistency across components
export interface Employee {
  id: string;
  sNo: number;
  salutation: string;
  name: string;
  employeeId: string;
  position: string;
  department: string;
  status: string;
  email: string;
  reportingManager: string;
}

export const EMPLOYEES: Employee[] = [
  {
    id: '1',
    sNo: 1,
    salutation: 'Mr.',
    name: 'Arjun Joshi',
    employeeId: 'INT-EMP-9322',
    position: 'Chief Product Officer (CPO)',
    department: 'Product',
    status: 'Pending',
    email: 'arjun.joshi@introlligent.com',
    reportingManager: 'Meera Goel',
  },
  {
    id: '2',
    sNo: 2,
    salutation: 'Mr.',
    name: 'Rohan Iyer',
    employeeId: 'INT-EMP-7551',
    position: 'Chief Technology Officer (CTO)',
    department: 'Engineering',
    status: 'In Progress',
    email: 'rohan.iyer@introlligent.com',
    reportingManager: 'Meera Goel',
  },
  {
    id: '3',
    sNo: 3,
    salutation: 'Mr.',
    name: 'Kunal Monga',
    employeeId: 'INT-EMP-9642',
    position: 'Chief Information Officer (CIO)',
    department: 'IT',
    status: 'In Progress',
    email: 'kunal.monga@introlligent.com',
    reportingManager: 'Rohan Iyer',
  },
  {
    id: '4',
    sNo: 4,
    salutation: 'Ms.',
    name: 'Nisha Chawla',
    employeeId: 'INT-EMP-9913',
    position: 'Chief Operating Officer (COO)',
    department: 'Operations',
    status: 'Pending',
    email: 'nisha.chawla@introlligent.com',
    reportingManager: 'Meera Goel',
  },
  {
    id: '5',
    sNo: 5,
    salutation: 'Mr.',
    name: 'Kabir Joshi',
    employeeId: 'INT-EMP-2197',
    position: 'Head of Customer Success',
    department: 'Customer Success',
    status: 'Completed',
    email: 'kabir.joshi@introlligent.com',
    reportingManager: 'Minal Monga',
  },
  {
    id: '6',
    sNo: 6,
    salutation: 'Ms.',
    name: 'Swati Khandelwal',
    employeeId: 'INT-EMP-5921',
    position: 'IT Support Lead',
    department: 'IT',
    status: 'In Progress',
    email: 'swati.khandelwal@introlligent.com',
    reportingManager: 'Kunal Monga',
  },
  {
    id: '7',
    sNo: 7,
    salutation: 'Ms.',
    name: 'Simran Gupta',
    employeeId: 'INT-EMP-2642',
    position: 'Chief Financial Officer (CFO)',
    department: 'Finance',
    status: 'Completed',
    email: 'simran.gupta@introlligent.com',
    reportingManager: 'Meera Goel',
  },
  {
    id: '8',
    sNo: 8,
    salutation: 'Ms.',
    name: 'Sneha Rao',
    employeeId: 'INT-EMP-3637',
    position: 'Frontend Lead',
    department: 'Engineering',
    status: 'Pending',
    email: 'sneha.rao@introlligent.com',
    reportingManager: 'Rohan Iyer',
  },
  {
    id: '9',
    sNo: 9,
    salutation: 'Ms.',
    name: 'Minal Monga',
    employeeId: 'INT-EMP-3326',
    position: 'Chief Revenue Officer (CRO)',
    department: 'Sales',
    status: 'Completed',
    email: 'minal.monga@introlligent.com',
    reportingManager: 'Nisha Chawla',
  },
  {
    id: '10',
    sNo: 10,
    salutation: 'Ms.',
    name: 'Meera Goel',
    employeeId: 'INT-EMP-5601',
    position: 'Chief Executive Officer (CEO)',
    department: 'Executive',
    status: 'Completed',
    email: 'meera.goel@introlligent.com',
    reportingManager: '',
  },
  {
    id: '11',
    sNo: 11,
    salutation: 'Ms.',
    name: 'Ritika Sharma',
    employeeId: 'INT-EMP-1135',
    position: 'Software Engineer II (Backend)',
    department: 'Engineering',
    status: 'Completed',
    email: 'ritika.sharma@introlligent.com',
    reportingManager: 'Rohan Iyer',
  },
  {
    id: '12',
    sNo: 12,
    salutation: 'Mr.',
    name: 'Tushar Mehta',
    employeeId: 'INT-EMP-1187',
    position: 'UI Developer',
    department: 'Engineering',
    status: 'Completed',
    email: 'tushar.mehta@introlligent.com',
    reportingManager: 'Sneha Rao',
  },
  {
    id: '13',
    sNo: 13,
    salutation: 'Ms.',
    name: 'Sneha Patel',
    employeeId: 'INT-EMP-1223',
    position: 'Content Strategist',
    department: 'Sales',
    status: 'In Progress',
    email: 'sneha.patel@introlligent.com',
    reportingManager: 'Minal Monga',
  },
  {
    id: '14',
    sNo: 14,
    salutation: 'Mr.',
    name: 'Ankit Verma',
    employeeId: 'INT-EMP-1261',
    position: 'System Administrator',
    department: 'IT',
    status: 'Completed',
    email: 'ankit.verma@introlligent.com',
    reportingManager: 'Swati Khandelwal',
  },
  {
    id: '15',
    sNo: 15,
    salutation: 'Ms.',
    name: 'Kavita Menon',
    employeeId: 'INT-EMP-1302',
    position: 'Operations Coordinator',
    department: 'Operations',
    status: 'Pending',
    email: 'kavita.menon@introlligent.com',
    reportingManager: 'Nisha Chawla',
  },
];
